language: r
cache: packages

after_success:
    - Rscript -e 'covr::codecov(function_exclusions = c("single_chapter_addin", "thesis_epub", "thesis_Word", "thesis_gitbook"))'

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true